SpiNNakerManchester/PACMAN

- pacman/operations/router_check_functionality/valid_routes_checker.py
added a progress bar to the vqalid route checker and cleaned up imports.
> added a progress bar to the valid route checker

- pacman/model/abstract_classes/abstract_virtual_vertex.py
- pacman/operations/abstract_algorithms/abstract_chip_id_allocator_algorithm.py
- pacman/operations/chip_id_allocator_algorithms/malloc_based_chip_id_allocator.py
- unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
Fixes issues with SpiNNakerLink functionality
> Fix spinnaker links

- pacman/operations/chip_id_allocator_algorithms/malloc_based_chip_id_allocator.py
- pacman/utilities/algorithm_utilities/machine_algorithm_utilities.py
- pacman/utilities/utility_objs/resource_tracker.py
> Create only 1 virtual chip per link_id

- pacman/model/abstract_classes/abstract_constrained_edge.py
- pacman/operations/pacman_algorithm_executor.py
- setup.py
on-chip data specification executor
> C data spec

- pacman/operations/algorithms_metadata.xml
- pacman/operations/partition_algorithms/basic_partitioner.py
- pacman/operations/partition_algorithms/partition_and_place_partitioner.py
Fixes the allocation of boards by providing the number of chips
> allocation fix

- pacman/model/abstract_classes/abstract_virtual_vertex.py
- pacman/operations/algorithm_reports/reports.py
- pacman/operations/placer_algorithms/radial_placer.py
- pacman/utilities/algorithm_utilities/machine_algorithm_utilities.py
- pacman/utilities/utility_objs/resource_tracker.py
> Spinnaker tools changes

- pacman/operations/placer_algorithms/one_to_one_placer.py
- pacman/utilities/utility_objs/resource_tracker.py
> Fix one to one placer

- pacman/executor/algorithm_decorators/algorithm_decorator.py
> fix for packager scanner

- pacman/executor/injection_decorator.py
Injections now work for Breakout
> Fixed check for None in injection

- doc/doc_requirements.txt
- doc/source/conf.py
using sphinx.apidoc.main works
> directly use sphinx.autodoc.main

- pacman/executor/algorithm_classes/python_class_algorithm.py
- pacman/executor/algorithm_classes/python_function_algorithm.py
- unittests/model_tests/algorithm_classes_tests/python_class_algorithm_tests.py
- unittests/model_tests/algorithm_classes_tests/python_function_algorithm_tests.py
Very simple cleanup and tested.
> removed duplicate slot in class and super class

- pacman/model/graphs/common/constrained_object.py
- pacman/operations/algorithm_reports/network_specification.py
- pacman/utilities/file_format_converters/convert_to_file_core_allocations.py
- pacman/utilities/file_format_converters/convert_to_file_machine_graph.py
- uinit_test_objects/test_partitioning_constraint.py
- uinit_test_objects/test_vertex.py
- unittests/model_tests/application_graph_tests/test_application_edge.py
- unittests/model_tests/application_graph_tests/test_application_graph.py
- unittests/model_tests/application_graph_tests/test_application_vertex.py
- unittests/model_tests/graph_mapper_tests/test_graph_mapper.py
- unittests/model_tests/graph_mapper_tests/test_slice.py
- unittests/model_tests/placement_tests/test_placement_object.py
- unittests/model_tests/placement_tests/test_placements_model.py
- unittests/model_tests/resources_tests/test_resources_model.py
- unittests/model_tests/routing_table_tests/test_multi_cast_routing_entry.py
- unittests/model_tests/routing_table_tests/test_routing_tables_model.py
- unittests/model_tests/tag_tests/test_tag_infos_model.py
- unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
- unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
Is this low-hanging fruit that could be just knocked off?
> minor fixes to doc strings

- pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/malloc_based_routing_info_allocator.py
Fixes:
https://github.com/SpiNNakerManchester/PACMAN/issues/96
> fixed bug found by numpy update for zero remaining zeros

- pacman/operations/algorithm_reports/reports.py
This reworks the code to stop using dictionaries of dictionaries. The use of constant string keys was particularly ugly!
**NB:** Needs someone to check that the tricks used actually work.
> Updated to be more useful

- pacman/operations/algorithm_reports/reports_metadata.xml
- pacman/operations/algorithms_metadata.xml
- pacman/operations/algorithms_metadata_schema.xsd
- pacman/operations/rigs_algorithm_metadata.xml
- pacman/utilities/file_format_converters/converter_algorithms_metadata.xml
This is the _actual_ schema used by the XML algorithm description files.
(FEC and sPyNNaker can't be changed to use the schema until we have the updated schema available properly on github.)
> Schema update

- .travis.yml
- pacman/executor/algorithm_metadata_xml_reader.py
- pacman/operations/algorithm_reports/reports_metadata.xml
- pacman/operations/algorithms_metadata.xml
- pacman/operations/algorithms_metadata_schema.xsd
- pacman/operations/rigs_algorithm_metadata.xml
- pacman/utilities/file_format_converters/converter_algorithms_metadata.xml
Further work on the schema to support the XML as found in the rest of the sPyNNaker stack
> Schema urls

- pacman/model/graphs/impl/graph.py
added a order dict for edges, as it iterates over items there. could be a point of inconsistencies
> more attempt at consistency

- pacman/operations/algorithms_metadata.xml
- pacman/operations/fixed_route_router/fixed_route_router.py
this algorithm assumes there's a thing on the Ethernet connected chip that its going to, and that its board parallel. 
It build a very simple set of paths which spreads the cost over the links on the Ethernet connected chip. 
Could be useful in the data unloading aspect, and was a 15 minute write.
> new algorithm for fixed route routers.

- .gitignore
- pacman/operations/router_algorithms/basic_dijkstra_routing.py
- unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
This reworks the code to stop using dictionaries of dictionaries. The use of constant string keys was particularly ugly!
**NB:** Needs someone to check that the tricks used actually work.
> Redo the internal data structures to use slotted objects

- pacman/operations/algorithm_reports/reports.py
- pacman/utilities/file_format_converters/convert_to_file_machine_graph.py
- pacman/utilities/file_format_converters/convert_to_file_machine_graph_pure_multicast.py
gives us a 5.4 times speed up on simple synfire chain. likely to give more for larger sims. 
depends upon the following prs:
Note that this work is not finished, but is stable. Future work will come which will increase this even further
> Speed up data extractor

- pacman/operations/algorithm_reports/reports.py
- pacman/operations/algorithms_metadata.xml
- pacman/operations/fixed_route_router/fixed_route_router.py
allows us to adapt to dead chips.
> fixes fixed route router

- pacman/operations/algorithm_reports/reports.py
- pacman/operations/algorithm_reports/reports_metadata.xml
- pacman/operations/algorithm_reports/routing_compression_checker_report.py
- unittests/operations_tests/router_compressor_tests/test_mundy_compressor.py
Added a report which compares the compressed and uncompressed routing tables.
It check that every possible route in the uncompressed one is correctly covered in the compressed one.
> Compression report

- pacman/executor/algorithm_decorators/abstract_input.py
- pacman/executor/algorithm_decorators/all_of_input.py
- pacman/executor/algorithm_decorators/one_of_input.py
- pacman/executor/algorithm_decorators/single_input.py
- pacman/executor/pacman_algorithm_executor.py
- pacman/operations/algorithms_metadata.xml
- unittests/test_pacman_algorithm_executor.py
This deals better with the optional inputs of algorithms where the input is also an output of that algorithm.  If there are no algorithms that can otherwise generate this input, the input is considered truly optional.
> Fix recursive optionals

- pacman/executor/pacman_algorithm_executor.py
- pacman/operations/algorithms_metadata.xml
Fixes partitioning when not using extra monitor support
> Fix partitioning

- pacman/operations/fixed_route_router/fixed_route_router.py
supports detecting dead links (just in case)
and also now removes many magic numbers and thus exploits the following pr
https://github.com/SpiNNakerManchester/SpiNNMachine/pull/60
> Fixed router checks for dead links also

- pacman/executor/algorithm_classes/external_algorithm.py
- pacman/executor/algorithm_classes/python_class_algorithm.py
- pacman/executor/algorithm_classes/python_function_algorithm.py
Updated to remove large inputs in error message - now just the input names are displayed
> better error messages

- pacman/model/graphs/abstract_graph.py
- pacman/model/graphs/impl/graph.py
- pacman/model/resources/iptag_resource.py
- requirements-test.txt
allows the graph to track what edge is assocated with each partition. used by nengo extensively.
> Partition map by edge

- pacman/executor/algorithm_decorators/algorithm_decorator.py
- pacman/executor/injection_decorator.py
- pacman/executor/pacman_algorithm_executor.py
- pacman/model/graphs/common/graph_mapper.py
- pacman/model/graphs/impl/graph.py
- pacman/model/placements/placements.py
- pacman/model/routing_table_by_partition/multicast_routing_table_by_partition.py
- pacman/model/routing_tables/multicast_routing_table.py
- pacman/model/tags/tags.py
- pacman/operations/algorithm_reports/routing_compression_checker_report.py
- pacman/operations/multi_cast_router_check_functionality/valid_routes_checker.py
- pacman/operations/placer_algorithms/radial_placer.py
- pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/compressible_malloc_based_routing_info_allocator.py
- pacman/utilities/file_format_converters/convert_to_file_core_allocations.py
- pacman/utilities/file_format_converters/convert_to_file_machine.py
- pacman/utilities/file_format_converters/convert_to_file_machine_graph.py
- pacman/utilities/file_format_converters/convert_to_file_machine_graph_pure_multicast.py
- pacman/utilities/utility_objs/resource_tracker.py
- pacman/utilities/vertex_sorter.py
- setup.py
- unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
- unittests/operations_tests/router_compressor_tests/test_mundy_compressor.py
- unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75
> Deprecation warning

- pacman/operations/algorithm_reports/reports.py
Required by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/196 but can be merged before.
> give different reports different names!

- pacman/operations/placer_algorithms/one_to_one_placer.py
- pacman/operations/placer_algorithms/radial_placer.py
- pacman/utilities/utility_objs/resource_tracker.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/628.
@Christian-B if you want to test your script then this is the branch.
> Fix radial placer to use constraints properly

- pacman/utilities/utility_calls.py
A small change to allow the rest of the structural plasticity branches to work. @rowleya I'm not completely sure if this could have been avoided somehow, but also if I miss something. 
The purpose of this PR is also to add to the Structural plasticity project so we can keep track of all the changes.
> Structural plasticity 

- pacman/utilities/algorithm_utilities/machine_algorithm_utilities.py
- pacman/utilities/file_format_converters/convert_to_java_machine.py
- pacman/utilities/file_format_converters/converter_algorithms_metadata.xml
- pacman/utilities/file_format_schemas/jmachine.json
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/372
All none PACMAN specific comments there.
All merges to be done at the same time.
Replaces https://github.com/SpiNNakerManchester/PACMAN/pull/187 so addresses the comments made there.
> Extractor2

- pacman/operations/placer_algorithms/one_to_one_placer.py
Fix for https://github.com/SpiNNakerManchester/sPyNNaker8/pull/196
> fix for multiple virtual placements on same virtual "chip"

- pacman/operations/fixed_route_router/fixed_route_router.py
- unittests/test_fixed_route_router.py
This is the factored out code mentioned in SpiNNakerManchester/SpiNNMachine#105
> Using the create_one_board_machine function from spinn_machine

- pacman/operations/fixed_route_router/fixed_route_router.py
- pacman/utilities/file_format_converters/convert_to_java_machine.py
- pacman/utilities/utility_objs/resource_tracker.py
- unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
- unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
- unittests/operations_tests/partition_algorithms_tests/test_partitioner_with_pre_allocated_resources.py
- unittests/operations_tests/placer_algorithms_tests/test_one_to_one_placer.py
- unittests/operations_tests/placer_algorithms_tests/test_same_chip_constraint.py
- unittests/operations_tests/placer_algorithms_tests/test_sdram_edge_placement.py
- unittests/operations_tests/placer_algorithms_tests/test_virtual_placement.py
- unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
- unittests/operations_tests/router_algorithms_tests/test_generic_router.py
- unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
- unittests/test_fixed_route_router.py
- unittests/utilities_tests/test_format_converters.py
- unittests/utilities_tests/test_resource_tracker.py
Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/104
> Wrapped machine

- pacman/operations/algorithm_reports/reports_metadata.xml
Accompanying FEC branch to follow...
> Rename misspelt report

- pacman/utilities/utility_objs/resource_tracker.py
Given that I keep getting this error on larger boards I decided to fix the spelling mistake...
> Minor spelling mistake

- pacman/operations/algorithm_reports/reports.py
> total_compressed

- pacman/operations/algorithm_reports/reports.py
#243 didn't do the trick, but this does…
> Fix the divide by zero problem for real this time

- pacman/utilities/algorithm_utilities/machine_algorithm_utilities.py
- unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
- unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
- unittests/operations_tests/placer_algorithms_tests/test_basic_placer.py
- unittests/operations_tests/placer_algorithms_tests/test_radial_placer.py
part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/120
> router clock speed was wrong and unused so hammer applied

- pacman/operations/router_algorithms/ner_route.py
tested with https://github.com/SpiNNakerManchester/sPyNNaker8/pull/267
> Nuke broken unused Mundy algorithm

- pacman/executor/injection_decorator.py
- pacman/executor/pacman_algorithm_executor.py
- pacman/model/graphs/impl/graph.py
- pacman/model/placements/placements.py
- pacman/model/routing_table_by_partition/multicast_routing_table_by_partition.py
- pacman/model/routing_tables/multicast_routing_table.py
- pacman/model/routing_tables/multicast_routing_tables.py
- pacman/model/tags/tags.py
- pacman/operations/algorithm_reports/routing_compression_checker_report.py
- pacman/operations/multi_cast_router_check_functionality/valid_routes_checker.py
- pacman/operations/placer_algorithms/radial_placer.py
- pacman/operations/router_compressors/clash_compressor.py
- pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/compressible_malloc_based_routing_info_allocator.py
- pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
- pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
- pacman/utilities/algorithm_utilities/routing_info_allocator_utilities.py
- pacman/utilities/json_utils.py
- pacman/utilities/utility_objs/resource_tracker.py
- setup.py
- unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
- unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
https://github.com/SpiNNakerManchester/SpiNNUtils/issues/102
> fixed incorrect import from collections.abc

- unittests/utilities_tests/test_json_utils.py
Constraints were not always coming out of deserialisation in the same order they were put into serialisation, which meant that the pairwise comparison was failing despite the constraints really representing a set in the first place. Which was dumb. (This was causing sporadic failures during integration testing.)
Also made the code easier to read.
> Stabilise the JSON test code

- pacman/model/graphs/impl/graph.py
Make vertices a set to make adding edges quicker
> Make vertices set again

- .gitignore
- pacman/model/graphs/machine/machine_vertex.py
- pacman/operations/placer_algorithms/one_to_one_placer.py
- pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
- unittests/operations_tests/placer_algorithms_tests/test_same_chip_constraint.py
I overheard that the one-to-one placer is unacceptably slow, so I had a look at it to see if there were any reasonably simple fixes that could be done. There were a few.
> Try to make the 1-to-1 placer faster

- pacman/operations/fixed_route_router/fixed_route_router.py
- pacman/utilities/algorithm_utilities/machine_algorithm_utilities.py
- pacman/utilities/utility_objs/resource_tracker.py
- unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
- unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
- unittests/operations_tests/placer_algorithms_tests/test_basic_placer.py
- unittests/operations_tests/placer_algorithms_tests/test_one_to_one_placer.py
- unittests/operations_tests/placer_algorithms_tests/test_radial_placer.py
- unittests/operations_tests/placer_algorithms_tests/test_spreader_placer.py
- unittests/operations_tests/placer_algorithms_tests/test_virtual_placement.py
- unittests/utilities_tests/test_resource_tracker.py
Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/124
> Max cores per chip

- pacman/utilities/utility_objs/resource_tracker.py
gives a better error message for when a core constraint is not possible:
As much as I plan to do for https://github.com/SpiNNakerManchester/PACMAN/issues/268
> better error meesgae on core constraint

- pacman/model/routing_info/base_key_and_mask.py
- pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
This makes the ZonedKeyAllocator work; it was a little bit broken due to slight mis-calculations in the key space.
> Fix zoned allocator

- pacman/operations/placer_algorithms/spreader_placer.py
This has been broken for 10 months...
> un-Alan the Spreader Placer

- pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
the order of the for stack was just weird.
> Partition order

- .travis.yml
- setup.py
Also run each version with best choice of Ubuntu distribution
> Add testing with Python 3.8

- pacman/model/partitioner_interfaces/__init__.py
- pacman/model/partitioner_interfaces/abstract_slices_connect.py
- pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
This changes from creating MaachineEdges to later filter them away to never creating them.
Must be done at the same time as:
https://github.com/SpiNNakerManchester/sPyNNaker/pull/847
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/427
Also found incorrect algorithm list removed in 
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/640
https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/147
(These prs can be done at anytime)
> Pre filter

- pacman/operations/algorithm_reports/reports.py
- pacman/operations/algorithm_reports/reports_metadata.xml
- pacman/operations/algorithms_metadata.xml
another graph mapper legacy issue
> makes partitioning report go in right place

- pacman/model/resources/constant_sdram.py
- pacman/model/resources/cpu_cycles_per_tick_resource.py
- pacman/model/resources/dtcm_resource.py
- pacman/model/resources/multi_region_sdram.py
- pacman/model/resources/variable_sdram.py
This hides the issue in https://github.com/SpiNNakerManchester/PACMAN/issues/320
> convert numpy integer to int

- .github/workflows/python_actions.yml
- .ratexcludes
- doc/source/conf.py
- pacman/model/graphs/application/application_edge.py
- pacman/model/resources/abstract_sdram.py
- pacman/model/resources/constant_sdram.py
- pacman/model/resources/cpu_cycles_per_tick_resource.py
- pacman/model/resources/multi_region_sdram.py
- pacman/model/routing_tables/__init__.py
- pacman/model/routing_tables/abstract_multicast_routing_table.py
- pacman/model/routing_tables/compressed_multicast_routing_table.py
- pacman/model/routing_tables/uncompressed_multicast_routing_table.py
- pacman/operations/algorithm_reports/reports.py
- pacman/operations/algorithm_reports/write_json_machine_graph.py
- pacman/operations/routing_info_allocator_algorithms/destination_based_key_allocator.py
- pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
- pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
- requirements-test.txt
- requirements.txt
- setup.py
Includes https://github.com/SpiNNakerManchester/PACMAN/pull/325
So when this goes in close that too
> turn on python actions

- doc/source/conf.py
- pacman/model/graphs/application/application_edge.py
- pacman/model/resources/abstract_sdram.py
- pacman/model/resources/constant_sdram.py
- pacman/model/resources/cpu_cycles_per_tick_resource.py
- pacman/model/resources/multi_region_sdram.py
- pacman/model/routing_tables/__init__.py
- pacman/model/routing_tables/abstract_multicast_routing_table.py
- pacman/model/routing_tables/compressed_multicast_routing_table.py
- pacman/model/routing_tables/uncompressed_multicast_routing_table.py
- pacman/operations/algorithm_reports/reports.py
- pacman/operations/algorithm_reports/write_json_machine_graph.py
- pacman/operations/routing_info_allocator_algorithms/destination_based_key_allocator.py
- pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
- pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
This fixes the Sphinx documentation build to be clean and correctly linked.
> Fix Python documentation

- pacman/model/graphs/application/application_fpga_vertex.py
- pacman/model/graphs/application/application_spinnaker_link_vertex.py
- pacman/model/graphs/application/application_vertex.py
- uinit_test_objects/simple_test_vertex.py
- unittests/model_tests/application_graph_tests/test_application_vertex.py
Fixes https://github.com/SpiNNakerManchester/PACMAN/issues/320
> Application Vertices should make sure n_atoms is an int

- pacman/operations/router_compressors/clash_compressor.py
The current state is the docs lines are too long so a pr merge should block.
But no real damage it it does not.
> added some docs

- pacman/operations/router_algorithms/ner_route.py
- unittests/operations_tests/router_algorithms_tests/test_ner_route_default.py
Adds an incoming route, allowing the detection of default routes
> Lost spike issues

- pacman/spinnaker.cfg
part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/159
> Router max entries from Machine

- pacman/model/partitioner_splitters/splitter_reset.py
- pacman/operations/algorithms_metadata.xml
- pacman/operations/placer_algorithms/one_to_one_placer.py
- pacman/utilities/utility_objs/resource_tracker.py
A couple of extra things needed for this to pass tests correctly
> Split synapse neuron models

- pacman/utilities/utility_objs/resource_tracker.py
once you have more than 60 chips the per chip is not interesting.
Could have a max but I imagine we will never hit this with more than 1 board
> reduce the error message once you hit more than 60 chips.

- requirements.txt
- setup.py
fixes https://github.com/SpiNNakerManchester/PACMAN/issues/417
> SpinUtils imports numpy so no need to repeat complicated here

- requirements.txt
- setup.py
tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/109
> removed lxml requirement

- .pylintrc
Same as https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/946
> removed no-space-check

- requirements.txt
- setup.py
tested by: https://github.com/SpiNNakerManchester/sPyNNaker/actions/runs/3218904093
> importlib-resources < 5.10.0; python_version == '3.6'

- pacman/operations/placer_algorithms/application_placer.py
part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/198
not tested as these report rarely written.
Can be merged before but not after
> fix report_dir errors

- pacman/model/graphs/abstract_edge_partition.py
- pacman/model/graphs/application/application_edge_partition.py
- pacman/model/graphs/application/application_vertex.py
Adds the ability to be notified when an incoming edge is added
> Spif output

- .github/workflows/python_actions.yml
- requirements.txt
- setup.py
Drop python 3.6 as described in https://github.com/SpiNNakerManchester/SupportScripts/pull/43
> Remove 3.6

- pacman/model/graphs/common/mdslice.py
- pacman/model/graphs/common/slice.py
Something went wrong with the documentation for Slice (and MDSlice). This fixes it.
> Fix docs of slices

- pacman/_version.py
- setup.cfg
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/236
> Version bump

- unittests/model_tests/routing_table_tests/test_routing_tables_model.py
- unittests/operations_tests/router_compressor_tests/test_compressors.py
Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/225
Cherry pick from https://github.com/SpiNNakerManchester/PACMAN/pull/513
> name optional parameters now required.

- pacman/model/graphs/application/application_2d_fpga_vertex.py
- pacman/model/graphs/application/application_2d_spinnaker_link_vertex.py
- pacman/model/graphs/common/mdslice.py
- pacman/model/graphs/common/slice.py
- pacman/model/graphs/machine/constant_sdram_machine_partition.py
- pacman/model/graphs/machine/machine_edge.py
- pacman/model/graphs/machine/simple_machine_vertex.py
- pacman/model/partitioner_splitters/abstract_splitter_common.py
- pacman/model/partitioner_splitters/splitter_external_device.py
- pacman/model/partitioner_splitters/splitter_one_app_one_machine.py
- pacman/model/partitioner_splitters/splitter_one_to_one_legacy.py
- pacman/model/resources/constant_sdram.py
- pacman/model/resources/multi_region_sdram.py
- pacman/model/resources/variable_sdram.py
- pacman_test_objects/simple_test_vertex.py
- unittests/model_tests/machine_graph_tests/test_partitions.py
- unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/257
typing changes only
> Overrides check

- unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/244
Or even if the above does not go in!
> only expose processor virtual ids 

- pacman/data/pacman_data_view.py
- pacman/data/pacman_data_writer.py
- pacman/operations/placer_algorithms/application_placer.py
- unittests/data/test_data.py
- unittests/operations_tests/placer_algorithms_tests/test_application_placer.py
- unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/245
> processor renaming

- unittests/operations_tests/placer_algorithms_tests/test_application_placer.py
- unittests/operations_tests/router_algorithms_tests/test_routers.py
- unittests/operations_tests/router_compressor_tests/test_checked_unordered_pair_compression.py
- unittests/operations_tests/router_compressor_tests/test_ordered_covering_compression.py
- unittests/operations_tests/router_compressor_tests/test_pair_compression.py
- unittests/operations_tests/router_compressor_tests/test_range_compressor.py
- unittests/operations_tests/router_compressor_tests/test_unordered_pair_compression.py
- unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/260
> Version248

- .github/workflows/python_actions.yml
- pacman/operations/router_algorithms/application_router.py
SupportScripts python_checks
python 3.13 is known to fail and know why https://github.com/SpiNNakerManchester/PACMAN/issues/561
Leaving test running so we see when it starts to work.
One minor pylint fix
Variable could be used before initialised
> test using 

- .github/workflows/python_actions.yml
part of https://github.com/SpiNNakerManchester/sPyNNaker/pull/1455
> coverage-package pylint-packages mypy-packages

- pacman/operations/placer_algorithms/application_placer.py
- unittests/operations_tests/placer_algorithms_tests/test_application_placer.py
This is in preparation of having SDRAM objected with shared memory
Moves the summing of SDRAM to the SDRAM Classes.
These will assume that if two SDRAm objects are being added they are on the same Chip
> Let SDRAM objects do the sum

- pacman/model/resources/shared_sdram.py
Fix an issue where shared SDRAM was not adding up correctly
> Fix shared sdram

- pacman/utilities/utility_objs/chip_counter.py
Part of https://github.com/SpiNNakerManchester/sPyNNaker/pull/1558
This ensures that groups of cores that have to be on a single chip can be.
> Split cores

- pacman/config_setup.py
- pacman/operations/placer_algorithms/application_placer.py
- pacman/operations/placer_algorithms/draw_placements.py
- pacman/pacman.cfg
- unittests/.gitignore
- unittests/data/test_data.py
- unittests/test_cfg_checker.py
builds on https://github.com/SpiNNakerManchester/PACMAN/pull/595
part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/299
> Cfg documentor

- unittests/test_doc_checker.py
part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/321
> Improved Doc checker
