- pacman/utilities/utility_objs/resource_tracker.py
This is mainly relevant for virtual populations that require 0 SDRAM on a virtual chip with 0 SDRAM, but is of course correct in general.
> Use >= in _is_sdram_available

- pacman/operations/algorithms_metadata.xml
- pacman/operations/routing_info_allocator_algorithms/destination_based_key_allocator.py
key allocator for destination routing. Can be used to generate research in different types of routing vs routing entry allocation and packets and speed of execution and performance in relation to packet reinjector. 
Given the research scope, I think it should be pushed into the tool chain for other end users to use (it seems people start by using this type of routing, and allowing them to be supported via the tool chain would be a reasonable ask)
> Destination routing

- integration_tests/test_same_chip_constraint.py
- pacman/model/graphs/abstract_virtual_vertex.py
- pacman/model/graphs/machine/impl/machine_vertex.py
- pacman/operations/algorithms_metadata.xml
- pacman/operations/partition_algorithms/basic_partitioner.py
- pacman/operations/partition_algorithms/partition_and_place_partitioner.py
- pacman/operations/placer_algorithms/one_to_one_placer.py
- pacman/operations/placer_algorithms/radial_placer.py
- pacman/operations/rig_algorithms/rig_place.py
- pacman/operations/tag_allocator_algorithms/basic_tag_allocator.py
- pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
- pacman/utilities/rig_converters.py
- pacman/utilities/utility_objs/resource_tracker.py
Adds support for specifying that a group of Machine vertices must be placed on the same chip.  Currently this is supported by the RadialPlacer and the OneToOnePlacer, as well as RigPlace.
> Same chip as constraint

- pacman/model/graphs/application/impl/application_vertex.py
- pacman/model/graphs/machine/impl/machine_fpga_vertex.py
- pacman/model/graphs/machine/impl/machine_spinnaker_link_vertex.py
- pacman/model/graphs/machine/impl/machine_vertex.py
- pacman/model/graphs/machine/impl/simple_machine_vertex.py
- pacman/utilities/utility_objs/resource_tracker.py
this set of branches works to remove the state region from recording. 
-IntroLab
-PACMAN
-FEC
-SPY
-GFE
-External
> recording no state region

- integration_tests/test_tags_board_addresses.py
- pacman/operations/tag_allocator_algorithms/basic_tag_allocator.py
- pacman/utilities/utility_objs/resource_tracker.py
- unittests/model_tests/tag_tests/test_tag_infos_model.py
Changes the allocation of IP tags and Reverse IP tags:
- Allow the allocation of a tag on any board in a set of boards
- Prefer the allocation of a tag on the board where the item is placed
- Updates to reflect changes in the IPTag interface
> Fix board addresses

- pacman/model/graphs/machine/impl/machine_outgoing_edge_partition.py
The superclass does what we want; stop doing it — wrongly — in the subclass.
> Fix machine edge partition traffic weights

- pacman/utilities/utility_objs/resource_tracker.py
Fix a couple of bugs including:
- Ethernet chips that are not connected cause issues
- Fix the error message when constrained chips don't have enough resources
- Allow allocation to all chips when ip tags are in use as these could be ok with tag sharing
> Fix missing ethernet ip address

- pacman/executor/pacman_algorithm_executor.py
Wild tracebacks are a problem; let's crush them where possible!
> Tracebacks should be done through the logger as much as possible

- pacman/model/graphs/abstract_graph.py
- pacman/model/graphs/impl/graph.py
- pacman/model/resources/pre_allocated_resource_container.py
- pacman/model/resources/specific_board_iptag_resource.py
- pacman/model/resources/specific_board_reverse_iptag_resource.py
- pacman/utilities/utility_objs/resource_tracker.py
this supports the pre allocation of iptags and reverse iptags. this should (i think) have been done during LPG stuff, but I only picked it up when starting the integration of the 15 speed up data extractor.
tested with spike io.
needs a FEC equiv brnach to be merged as well
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/226
togehter complete issue 
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/209
> supports pre allocation of iptags and reverse iptags

- pacman/model/graphs/common/graph_mapper.py
- pacman/operations/algorithms_metadata.xml
- pacman/operations/fixed_route_router/fixed_route_router.py
- pacman/operations/placer_algorithms/one_to_one_placer.py
allows the extra monitor core to use the fixed routes. Is tied to the following pull requests:
FEC, https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/220
SPinnMan, https://github.com/SpiNNakerManchester/SpiNNMan/pull/98
SpinnMachine, https://github.com/SpiNNakerManchester/SpiNNMachine/pull/52
GFE https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/68
need to all be merged at same time.
> supports fixed route router

- pacman/operations/router_algorithms/basic_dijkstra_routing.py
This is the possible fix to the problems with Dijkstra routing, making the weights default to infinity instead of None so that they are at least type-usable with math operations.
> Default uninitialised weights to infinity, not None

- pacman/operations/fixed_route_router/fixed_route_router.py
- unittests/test_fixed_route_router.py
This adds some tests and fixes some bugs in the fixed route router.  The main changes are:
- Fix an issue that meant that almost all boards were using the dynamic routing (since 0, 0, 4 doesn't exist on boards without wrap arounds).
- Force dynamic routing to stick to the board with the Ethernet chip that is being routed to.
> Fix fixed route down chips

- pacman/operations/algorithms_metadata.xml
- pacman/operations/partition_algorithms/partition_and_place_partitioner.py
Allows the use of spalloc with external devices, by ignoring virtual vertices until after partitioning; at this point we know how many (physical) chips we need, and so can get a real machine, and add the device chips.
> fix spalloc external devices

- pacman/model/constraints/partitioner_constraints/__init__.py
- pacman/model/constraints/partitioner_constraints/fixed_vertex_atoms_constraint.py
- pacman/operations/partition_algorithms/basic_partitioner.py
- pacman/operations/partition_algorithms/partition_and_place_partitioner.py
- unittests/model_tests/test_partition.py
- unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
- unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
Added a FixedAtomsPerCore constraint.  This enforces the splitting of an ApplicationVertex into fixed sized chunks.  Max atoms per core is ignored except to check that it is valid.
This works well on vertices where the concept of an atom has more meaning than just the subdivisability of the vertex in partitioning.
> Fixed atoms per core

- pacman/utilities/utility_objs/resource_tracker.py
this support the usage of sdram links etc much better, as we can now partition to a machine setup. Does assume that the spalloc max machine data is updated to include black listing
> Locate max cores of a chip

- pacman/model/graphs/impl/graph.py
- pacman/utilities/algorithm_utilities/machine_algorithm_utilities.py
- pacman/utilities/constants.py
- pacman/utilities/utility_objs/resource_tracker.py
this tracks the virtual chips separately to the real chips. It also makes the constant for n_cores_per_virtual_chips a actual constant, and not a magic number (who did that in the first place ;-) ) 
It should fix the issue arren was seeing. It also allows users to ask for the vc with the most usable cores.......if this is usful........im not sure......... but as it comes out of the changes. it might as well be put in.
> fixes screw up with resource tracker for virtual chips

- pacman/model/graphs/machine/machine_spinnaker_link_vertex.py
- pacman/operations/placer_algorithms/__init__.py
- pacman/operations/placer_algorithms/one_to_one_placer.py
- pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
- requirements-test.txt
- unittests/operations_tests/placer_algorithms_tests/test_one_to_one_placer.py
- unittests/operations_tests/placer_algorithms_tests/test_sdram_edge_placement.py
- unittests/operations_tests/placer_algorithms_tests/test_virtual_placement.py
- unittests/utilities_tests/test_format_converters.py
Fixes #190.  Replaces #191.
The issue turned out to be that the one-to-one placer was not ordering constraints correctly, so it was possible for it to assign vertices to a chip and then not have enough space for vertices constrained to be placed on that chip.
The fix required a fair amount of refactoring of the code, but I think it is in a better place for it, with easier to understand code (I hope).  Tests have also been added to test for the specific case, and for one-to-one placement in general.
> Fix virtual placement

- pacman/model/routing_table_by_partition/multicast_routing_table_by_partition_entry.py
- pacman/operations/fixed_route_router/fixed_route_router.py
- pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/compressible_malloc_based_routing_info_allocator.py
- pacman/operations/routing_table_generators/basic_routing_table_generator.py
- unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
puts it in line with the router table entry api, thus allowing functions that manipulate the router entry can be used to manuiplate the out going partition entry also. aka, router.convert_routing_table_entry_to_spinnaker_route. for nengo purposes of the graph colouring.
> api change to outgoing partition routing entry

- pacman/exceptions.py
- pacman/utilities/utility_objs/resource_tracker.py
Throw a different error if a chip is request that was not in the original list.
Required for https://github.com/SpiNNakerManchester/sPyNNaker8/pull/185
But can be merged before.
> Different error if chip used vs never in list to start with

- pacman/model/constraints/placer_constraints/chip_and_core_constraint.py
- pacman/model/graphs/application/application_spinnaker_link_vertex.py
- pacman/operations/algorithms_metadata.xml
Fix for https://github.com/SpiNNakerManchester/sPyNNaker8/issues/190.
> Deal with x, y = None case properly

- pacman/operations/placer_algorithms/one_to_one_placer.py
If you put constraints on all population there are no unallocated ones so calling 
self._allocate_one_to_one_group
makes no sense and give a weird exception.
found with:
import spynnaker8 as sim
from pacman.model.constraints.placer_constraints import (
ChipAndCoreConstraint)
sim.setup(timestep=1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 100)
input = sim.Population(10, sim.SpikeSourceArray(
spike_times=[0]), label="input")
input.set_constraint(ChipAndCoreConstraint(2, 2, 4))
pop_1 = sim.Population(10, sim.IF_curr_exp(), label="pop_1")
pop_1.set_constraint(ChipAndCoreConstraint(0, 0, 4))
input_proj = sim.Projection(input, pop_1, sim.OneToOneConnector(),
synapse_type=sim.StaticSynapse(weight=5, delay=1))
pop_2 = sim.Population(10, sim.IF_curr_exp(), label="pop_2") …
> no need to allocate a list of len 0

- pacman/operations/algorithms_metadata.xml
Currently GraphEdgeFilter is done before Routing just because it happens to be in the algorithm list before.
UGLY!
Now uses a token added in https://github.com/SpiNNakerManchester/sPyNNaker/pull/795 to ensure it is.
> Edge Filtered token

- pacman/model/resources/__init__.py
- pacman/model/resources/abstract_sdram.py
- pacman/model/resources/constant_sdram.py
- pacman/model/resources/multi_region_sdram.py
- pacman/model/resources/variable_sdram.py
- pacman/operations/algorithm_reports/reports.py
- unittests/model_tests/resources_tests/test_resources_model.py
Inspired by https://github.com/SpiNNakerManchester/PACMAN/pull/293
This provides a working of a dictionary based MultiRegionSDRAM
Allows the sdram cost to be assigned to specific causes and even nested
Unless the details are needed this acts like a normal VariableSDRAM
Different MultiRegionSDRAM can be combined using merge(..) which retains the dictionary.
Or even nested using the nest() method
However when doing add or sub the dictionary information is not retained as it is assumed that at a gobal level this is not interesting.
Added a report method to all sdram types so they can print/write to file in the most suitable way.
This PR is reguired for but can be merged before later PRs.
> Multi Region Sdram 

- pacman/model/graphs/machine/machine_vertex.py
In more than one place the code  makes the assumption that is get_n_keys_for_partition is not provided by the machine vertex than just use vertex_slice.n_atoms
Instead if that is assume just make it explict.
If someone really dislikes that there vertex which does not provides keys claims it does they can overwrite to throw NotImplemented 
In the current implementation the vertex can not control who assumes that get_n_keys_for_partition == vertex_slice.n_atoms
> Moved get_n_keys_for_partition to MachineVertex

- pacman/model/graphs/graph.py
- unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
- unittests/operations_tests/placer_algorithms_tests/test_connecitve_placer.py
We even have a unit test that claims
"test that adding the same machine edge will cause an error"
yet then checked that is can without an error.
tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/465
> Stop edges being added twice

- pacman/utilities/file_format_schemas/machine_graph.json
- unittests/utilities_tests/test_json_utils.py
Labels on edges are now optional in the schema.
vertex resource required is Not optional in the schema but even thought the marshalling will not fail if they are missing.
> Json edge label optional

- pacman/model/graphs/application/application_vertex.py
- pacman/model/graphs/machine/machine_graph.py
- pacman/model/graphs/machine/machine_vertex.py
- unittests/model_tests/application_graph_tests/test_application_vertex.py
- unittests/model_tests/graph_mapper_tests/test_graph_mapping.py
- unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
- unittests/utilities_tests/test_json_utils.py
To allow vertices and splitters create a machine Vertex before asked to or to cache it between runs the call to 
remember_associated_machine_vertex has been delayed until the vertex is added to the machine graph.
method name change to hard break anywhere in other branches that used it.
Note: tests of app_vertex.machine_vertices behaviour have been moved not removed.
Must be doen together with https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/678
tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/477
> remembering machine_vertex called by machine_graph

- pacman/model/graphs/machine/machine_graph.py
- unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
Better check if all or none of the machine vertices have app_vertex.
one test fix in https://github.com/SpiNNakerManchester/PACMAN/pull/312
tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/476
Note that @dkfellows and @rowleya wondered why this is needed.
Answer only a safety check.
> all or nothing for machinevertex.appvertex

- pacman/model/resources/variable_sdram.py
It seems that the ability for variable SDRAM to have a float value for the per-timestep SDRAM is used at points.
> Allow variable SDRAM to be a float

- requirements.txt
- setup.py
This is blocking downstream builds, and is caused by sortedcollections 2 (strictly 2.0.1 as 2.0.0 wasn't released) dropping Python 2.7 support. Which wasn't loudly announced.
> sortedcollections needs version restriction for Python 2.7

- pacman/executor/algorithm_decorators/algorithm_decorator.py
Can't use %s any more in logging messages, switching to "... {} .. ".format(..) instead.
Didn't find any more of these in this repository, will go through others and see if there's any there.
> Fix to print strings correctly, make messages more specific

- doc/source/conf.py
The config was only right with some versions of Sphinx; with the version deployed on readthedocs (1.8.5), it blew up (trying to split a boolean by commas, which doesn't work, whereas using `None` is fine).
None of this is at all helped by the fact that the configuration settings aren't very well described for programmatic use; there's a lot of outdated and plain bad descriptions out there. Sphinx's own documentation is good, but pretty much assumes that you hand-write everything in `.rst` files with all of the fiddly details all the time. Ain't _nobody_ got time for that!
> Write sphinx config right

- pacman/utilities/utility_objs/resource_tracker.py
found while investigation https://github.com/SpiNNakerManchester/SpiNNMachine/pull/155 but can be merged independent.
Why use a method that returns a chip to then ask the chip for its x and y when there is a cheaper method which returns xy directly.
> use get_existing_xys_by_ethernet as you just want xy

- doc/source/conf.py
- requirements-test.txt
Inlcudes fixes from https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/806
> Makes Sphinx more like other repo

- unittests/operations_tests/router_compressor_tests/test_checked_unordered_pair_compression.py
- unittests/operations_tests/router_compressor_tests/test_ordered_covering_compression.py
- unittests/operations_tests/router_compressor_tests/test_pair_compression.py
- unittests/operations_tests/router_compressor_tests/test_unordered_pair_compression.py
This is a f fix due to unittest not being able to find the default configs.
If a unitest depends on a config add.
```
def setUp(self):
reset_configs()
```
Where the reset_configs() comes from the config_setup,py in that repository
The get_config... calls normally just return a config value loaded when sim.setup() is run
If no sim.setup is run they will load configs logging a warning
To be able to load configs they have to know where they are.
The config files are added by a chain of add_xyz_cfg in each config_setup,py
The local reset_config() will 
1. clear any previous configs
2. call that change to define where the configs are.
Locally and in actions 1 unittest may find the config files from another test but to depend on this causes an BAD order dependency in tests.
Jenkins appears not …
> reset_configs

- pacman/operations/router_compressors/abstract_compressor.py
- pacman/operations/router_compressors/checked_unordered_pair_compressor.py
- pacman/operations/router_compressors/ordered_covering_router_compressor/ordered_covering.py
- pacman/operations/router_compressors/pair_compressor.py
- pacman/pacman.cfg
- pacman_integration_tests/manual_runner.py
- pacman_integration_tests/test_big_compression.py
- unittests/operations_tests/router_compressor_tests/test_checked_unordered_pair_compression.py
- unittests/operations_tests/router_compressor_tests/test_compressors.py
Removes the cfg router_table_compression_target_length dial.
Fixes: https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/793
Must be done at the same time as;
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/825
tested by
https://github.com/SpiNNakerManchester/IntegrationTests/pull/65
> Bye bye outer_table_compression_target_length setting

- pacman/model/graphs/application/application_vertex.py
- pacman/model/partitioner_interfaces/abstract_slices_connect.py
- pacman/operations/partition_algorithms/splitter_partitioner.py
Needed for https://github.com/SpiNNakerManchester/sPyNNaker/pull/1095
Application_vertex caching slices has two benefits
1. Avoid recreating then every time
2. FromListConnector  slices == slices is the id based
could_connect change to vertexes
1. Allows FromList to use __split_conn_list which is MUCH faster!
> Speedup Big FromListConnector 

- requirements.txt
python 2.7 is history!
why keep Futures import?
Must be done after
https://github.com/SpiNNakerManchester/SupportScripts/pull/40
https://github.com/SpiNNakerManchester/SpiNNGym/pull/41
https://github.com/SpiNNakerManchester/PyNN8Examples/pull/80
https://github.com/SpiNNakerManchester/microcircuit_model/pull/17
tested by 
https://github.com/SpiNNakerManchester/IntegrationTests/pull/108
> nuke future requirement

- pacman/model/graphs/abstract_multiple_partition.py
- pacman/model/graphs/application/application_graph.py
- pacman/model/graphs/graph.py
- pacman/model/graphs/machine/machine_graph.py
- pacman/model/partitioner_splitters/abstract_splitters/abstract_splitter_common.py
- pacman/model/placements/placements.py
- pacman/model/routing_table_by_partition/multicast_routing_table_by_partition.py
- pacman/model/routing_tables/multicast_routing_tables.py
- pacman/model/routing_tables/uncompressed_multicast_routing_table.py
- pacman/operations/partition_algorithms/splitter_partitioner.py
- pacman/operations/router_compressors/routing_compression_checker.py
- pacman/operations/routing_table_generators/zoned_routing_table_generator.py
- pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
- pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
- pacman/utilities/algorithm_utilities/routing_info_allocator_utilities.py
- pacman/utilities/json_utils.py
- pacman/utilities/vertex_sorter.py
As of python 3.7 (the first version we officially support) all dicts are now order guaranteed.
Even python 3.6 had it just not made if a guarantee
The OrderedDict and our DefaultOrderedDict have a few minor advantages
such as ability to iterate reversed. (python 3.8 normal dicts can but not 3.7 or 3.6)
Ability to .move_to_end() In normal dicts you have to remove and readded to get that affects
But are about 30% slower and do use more ram
ref: https://realpython.com/python-ordereddict/
This set of PRs changes the "ordered" to normal as far as possible.
They are all independent except that this PACMAN one must be done before (or at the same time as) the utils one!
OrderDict was kept in SpinUtils Ordered Sets as that supports reverse.
SpallocServer not done as 1. it uses move_to_end and 2 is …
> No need for "Ordered" dict

- .pylintrc
- pacman/executor/injection_decorator.py
- pacman/model/graphs/common/constrained_object.py
- pacman/model/partitioner_interfaces/legacy_partitioner_api.py
- pacman/model/partitioner_splitters/splitter_one_to_one_legacy.py
- pacman/model/partitioner_splitters/splitter_slice_legacy.py
- pacman/model/resources/multi_region_sdram.py
- pacman/model/routing_tables/uncompressed_multicast_routing_table.py
- pacman/operations/chip_id_allocator_algorithms/malloc_based_chip_id_allocator.py
- pacman/operations/fixed_route_router/fixed_route_router.py
- pacman/operations/partition_algorithms/splitter_partitioner.py
- pacman/operations/placer_algorithms/connective_based_placer.py
- pacman/operations/placer_algorithms/one_to_one_placer.py
- pacman/operations/placer_algorithms/radial_placer.py
- pacman/operations/placer_algorithms/spreader_placer.py
- pacman/operations/router_algorithms/basic_dijkstra_routing.py
- pacman/operations/router_algorithms/routing_tree.py
- pacman/operations/router_compressors/abstract_compressor.py
- pacman/operations/router_compressors/entry.py
- pacman/operations/router_compressors/ordered_covering_router_compressor/ordered_covering_compressor.py
- pacman/operations/router_compressors/pair_compressor.py
- pacman/operations/router_compressors/ranged_compressor.py
- pacman/utilities/algorithm_utilities/routing_info_allocator_utilities.py
- pacman/utilities/utility_calls.py
- unittests/operations_tests/partition_algorithms_tests/test_splitter_partitioner.py
More pylint fixes.
Turns off all global disables.
ConstrainedObject simplified as it is the only place _constraints is actually set
A few underscore method renamed to none underscore as called from outside
Many of the ._run calls could be converted from create object run object but that is out of scope here.
a few other minor fixes/ local disables,
> Pylint fix

- pacman/data/pacman_data_view.py
- pacman/model/placements/placements.py
The view.get_placement_on_processor  was missing and needed by ASB.__recover_from _error 
As view.get_vertex_on_processor differed only by where the .vertex was placed I choose to remove the get_vertex_on_processor from both Placements and View and instead replaced its only use with
view.get_placement_on_processor().vertex
Needed for: https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/979
> get_placement_on_processor

- pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
- pacman/utilities/utility_calls.py
Move the bits_needed function from the allocator to utility_calls for easier access from elsewhere.
Needed for https://github.com/SpiNNakerManchester/sPyNNaker/pull/1284
> Move bits_needed function into utility_calls

- requirements.txt
- setup.py
Another dependency has decided to end support for python 3.7.
For now a simple cap is all that is needed.
> jsonschema 4.17.3 last with python 3.7 support

- pacman/model/graphs/application/application_spinnaker_link_vertex.py
Fixes the max atoms per core on a SpiNNaker Link input device when the device is split into multiple "cores".  This helps sPyNNaker master population tables get the values right.
> Set the max atoms per core to something sensible

- pacman/model/graphs/abstract_edge.py
- pacman/model/graphs/abstract_edge_partition.py
- pacman/model/graphs/abstract_single_source_partition.py
- pacman/model/graphs/abstract_supports_sdram_edges.py
- pacman/model/graphs/abstract_vertex.py
- pacman/model/graphs/abstract_virtual.py
- pacman/model/graphs/application/application_2d_fpga_vertex.py
- pacman/model/graphs/application/application_edge.py
- pacman/model/graphs/application/application_edge_partition.py
- pacman/model/graphs/application/application_fpga_vertex.py
- pacman/model/graphs/application/application_graph.py
- pacman/model/graphs/application/application_vertex.py
- pacman/model/graphs/machine/abstract_sdram_partition.py
- pacman/model/graphs/machine/machine_edge.py
- pacman/model/graphs/machine/machine_vertex.py
- pacman/model/graphs/machine/multicast_edge_partition.py
- pacman/model/graphs/machine/source_segmented_sdram_machine_partition.py
- pacman/model/partitioner_splitters/abstract_splitters/abstract_splitter_common.py
- pacman/model/partitioner_splitters/splitter_external_device.py
It's important because inherited docs in FEC and sPyNNaker don't otherwise know which types to link to.
(Forgot to do this in #496)
> Things that are meant to be overridden need fully-qualified type names

- pacman/model/routing_tables/multicast_routing_tables.py
- pacman/operations/router_compressors/ranged_compressor.py
- unittests/operations_tests/routing_table_generator_tests/test_basic.py
- unittests/operations_tests/routing_table_generator_tests/test_merged.py
This fixes the max routing entries.
The previous way did not work as entries are added to tables after the tables are added to the dict.
Also adds a total for debugging
Must be done at the same time as.
> fix max_number_of_entries

- pacman/model/partitioner_splitters/abstract_splitter_common.py
This is a small change mainly designed to show that a change in the Typing branches is not needed.
In that pr there are two method to get the app vertex
governed_app_vertex which could return a None
_governed_app_vertex which never returns a None
This pr shows that governed_app_vertex can just not return None
If someone does need to check if the app vertex is not yet set we should add a has_app_vertex method.
tested by:
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/governed_app_vertex_never_none/1/pipeline
> when governed_app_vertex is requested it is no loner None

- pacman/model/graphs/abstract_vertex.py
- pacman/model/graphs/application/application_graph.py
- pacman/model/routing_tables/abstract_multicast_routing_table.py
- pacman/model/routing_tables/compressed_multicast_routing_table.py
- pacman/model/routing_tables/uncompressed_multicast_routing_table.py
- pacman/operations/fixed_route_router/fixed_route_router.py
- unittests/model_tests/application_graph_tests/test_application_vertex.py
For a Vextex
rename addedToGraph to setAddedToGraph - to show it is a setter not a getter
add has_been_added_to_graph which is the gtter for above
make add_multicast_routing_entry abstract in abstract routing table
-all implement it
-avoid needing to cast
needed for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1141
> fixes for FrontEndCommon typing

- pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
- unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
While working on validate_routes Pr found an error in a test which had two vertices with the same fixed key:
This adds a check that fixed keys and masks don't overlap.
Fixed a test where they dod to be one with and one wiithout overlap
Pr to fix the test is:
https://github.com/SpiNNakerManchester/sPyNNaker/pull/1418
tested by:
https://github.com/SpiNNakerManchester/IntegrationTests/pull/251
fixes: https://github.com/SpiNNakerManchester/PACMAN/issues/473
> Check fixed key and masks don't overlap

- pacman/utilities/json_utils.py
- unittests/utilities_tests/test_json_utils.py
The method to go from json to placement (currently usused) was wrong.
placement_from_json
It tried to get a vertex from a graph but placements need a MachineVertex and we no longer have a machine Graph.
So removed the option to load a vertex from the graph.
The rest of the changes are typing and testing
> fix placement json code

- .github/workflows/python_actions.yml
required for https://github.com/SpiNNakerManchester/PACMAN/issues/561
As you can not access matrix.python-version at the steps level higher than the steps 
https://github.com/SpiNNakerManchester/SupportScripts/commit/09acde67d8af65b260a8e544714e2e31807f5e3e
does an if in each step
this pr adds the flag check_prereleases: false
> skip  prereleases

- pacman/pacman.cfg
part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/274
> Cfg checker

- .github/workflows/python_actions.yml
- pacman/operations/placer_algorithms/_spinner_api.py
- pacman_test_objects/non_legacy_app_vertex.py
- pacman_test_objects/placer_test_support.py
- pacman_test_objects/py.typed
- pacman_test_objects/simple_test_vertex.py
- unittests/model_tests/partitioner_splitters_tests/splitter_slice_legacy_test.py
This and related Ps do more to unify the way we test.
All are independent but tested together.
Except the FEC one depends on this one.
General changes in several Repositories
1. mypy unittests
1. We still do not pylint unitests
1. install types-PyYAML so import yaml does not need a type: ignore 
1. minor changes to get tests to pass
1. Do not mypy matplot lib as the typed versions of matplotlib are python 3.9 and above
1. pylint: disable=no-name-in-module when using typing context Manager
- test show pylint is wrong in python 3.13
> github action fixes

- pacman/operations/router_algorithms/application_router.py
- pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
- pacman/utilities/algorithm_utilities/routing_algorithm_utilities.py
Fix some issues in using internal multicast partitions.  Mostly this makes sure that they are only applied when the partition id matches the partition being dealt with.  Changes here avoid changes elsewhere.
Tested by:
- SpiNNakerManchester/IntegrationTests#287
> Fix internal multicast partitions

- pacman/data/pacman_data_view.py
- pacman/model/placements/placements.py
- unittests/model_tests/placement_tests/test_placement_object.py
Iterate over more than one VertexType
Only a type change as isinstance accepts a tuple
Simplify https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1202
for https://github.com/SpiNNakerManchester/sPyNNaker/pull/1474
> Region downloading

- pacman/model/routing_info/routing_info.py
- pacman/operations/multi_cast_router_check_functionality/valid_routes_checker.py
- pacman/operations/routing_table_generators/basic_routing_table_generator.py
- pacman/operations/routing_table_generators/merged_routing_table_generator.py
- setup.cfg
- unittests/model_tests/routing_info_tests/test_routing_info.py
- unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
- unittests/operations_tests/routing_table_generator_tests/test_merged.py
Work to make sure partitions that vertices send using, and the partitions actually connected agree!
As the method is deprecated, the other PRs are not strictly necessary, but should avoid deprecation warnings:
- SpiNNakerManchester/SpiNNakerGraphFrontEnd#286
- SpiNNakerManchester/SpiNNFrontEndCommon#1219
- SpiNNakerManchester/sPyNNaker#1496
- SpiNNakerManchester/SpiNNGym#96
- SpiNNakerManchester/MarkovChainMonteCarlo#72
- SpiNNakerManchester/SpiNNaker_PDP2#89
- SpiNNakerManchester/TSPOnSpiNNaker#48
Tested by:
- SpiNNakerManchester/IntegrationTests#294
> Allow different partitions

- pacman/data/pacman_data_view.py
- pacman/model/resources/__init__.py
- pacman/model/resources/abstract_sdram.py
- pacman/model/resources/constant_sdram.py
- pacman/model/resources/multi_region_sdram.py
- pacman/model/resources/shared_sdram.py
- pacman/model/resources/variable_sdram.py
- pacman/utilities/json_utils.py
- unittests/model_tests/resources_tests/test_resources_model.py
- unittests/utilities_tests/test_json_utils.py
Designed to be used with https://github.com/SpiNNakerManchester/PACMAN/pull/581
Removals
1. Subtraction between sdram object
-Unused and make even less sense with SharedSdram
2. vertet json mehtods
- Unused. Can be replaced when the use case defines what is needed.
Changes.
1. eq defintion moved to each sdram
2. MultiRegionSDRAM now holds total as another sdram object
- Many methods delegated to that sdram object
4. MultiRegionSDRAM add_cost now uses nest method (as did the same thing)
5. add methods changed to handle the extra type
SharedSdram
-Takes a dict of keys to sdram Objects
- Optionally also a per_core sdram (mainly when summing)
> Shared sdram

- pacman/model/resources/iptag_resource.py
- pacman/model/tags/tags.py
- pacman/operations/tag_allocator_algorithms/basic_tag_allocator.py
required because of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/273
> assert not None

- pacman/model/partitioner_splitters/abstract_splitter_common.py
- pacman/model/routing_info/vertex_routing_info.py
- pacman/operations/router_algorithms/application_router.py
Replacing the uses of type
Union[MachineVertex, ApplicationVertex]
with AbstractVertex
mypy correctly does not handle a mix of the two 
includes:
https://github.com/SpiNNakerManchester/sPyNNaker/pull/1524
https://github.com/SpiNNakerManchester/BitBrainDemo/pull/68
https://github.com/SpiNNakerManchester/TSPonSpiNNaker/pull/53
> use AbstractVertex rather than Union
